before_script:
  - which git || (apt-get update -qq && apt-get install --no-install-recommends -qqqy git)
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/" --add
  - |
      julia -e '
      using Pkg
      Pkg.Registry.add(
        RegistrySpec(url = "https://github.com/JuliaRegistries/General.git")
      )
      Pkg.Registry.add(
        RegistrySpec(url = "https://gitlab.com/tensors4fields/tensors4fieldsregistry.git")
      )'

variables:
  CI_JULIA_CACHE_DIR: ${CI_PROJECT_DIR}/julia_pkg
  JULIA_DEPOT_PATH: ${CI_JULIA_CACHE_DIR}
cache:
  key:
    files:
      - Project.toml
    prefix: ${CI_JOB_NAME}
  paths:
    - ${CI_JULIA_CACHE_DIR}
    - _build

.jupyterbook:
  script:
    - |
      julia --project=@. -e 'using Pkg; Pkg.instantiate()'
      julia --project=@. run.jl
jupyterbook:
  image: julia:1.10.2
  extends:
    - .jupyterbook
  except:
    - main
pages:
  image: julia:1.10.2
  stage: deploy
  extends:
    - .jupyterbook
  after_script:
    - mkdir -p public
    - mv _build/html public/dev
  artifacts:
    paths:
      - public
  only:
    - main
