# ---
# jupyter:
#   jupytext:
#     cell_metadata_filter: -all
#     custom_cell_magics: kql
#     text_representation:
#       extension: .jl
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.11.2
#   kernelspec:
#     display_name: Julia 1.10.2
#     language: julia
#     name: julia-1.10
# ---

# %% [markdown]
# # PythonPlot
#
# [JuliaPy/PythonPlot.jl](https://github.com/JuliaPy/PythonPlot.jl) provides a Julia interface to the [Matplotlib](https://matplotlib.org/) plotting library from Python, and specifically to the matplotlib.pyplot module. This may be helpful for those who are new to Julia and come from Python.
#
# Consider that we have source code written in Python for plotting data like below:
#
# ```python
# from matplotlib import pyplot as plt
#
# fig, ax = plt.subplots()
# x = [1, 2, 3]
# y = [3, 1, 2]
# ax.plot(x, y, marker="+")
# ```
#
# With PythonPlot, porting this code to Julia is as simple as replacing the line `from matplotlib import pyplot as plt` with:
#
# ```julia
# using PythonPlot: pyplot as plt
# ```
#
# This allows us to use the familiar "plt syntax" within your Julia code.
#

# %%
using PythonPlot: pyplot as plt

fig, ax = plt.subplots()
x = [1, 2, 3]
y = [3, 1, 2]
ax.plot(x, y, marker="+")
# Use `display(fig)` as necessary
# display(fig)

# %% [markdown]
# ## Better plot handling
#
# As explained above, PythonPlot facilitates a smooth transition from Python to Julia for data visualization tasks. In this section, we provide valuable tips and tricks for experimenting with Julia and Jupyter Notebook or VS Code.
#

# %% [markdown]
# ### Difference between interactive and non-interactive session
#
# Normally, Julia running on Jupyter Notebook uses interactive session. The `isinteractive()` function
# tells us whether we are using interactive session or not.
#

# %%
# Check the following link for VS Code users
# https://github.com/microsoft/vscode-jupyter/issues/13493#issuecomment-1696484283
@doc isinteractive()

# %% [markdown]
# Let's see the output or `isinteractive()`
#

# %%
@show isinteractive();

# %% [markdown]
# Most users, including those viewing this notebook (generated by Jupyter Book) from a browser, will get `isinteractive() = true`.
# However there is one enrivonment that outputs `isinteractive() = false`. If we've installed Julia via [juliaup](https://github.com/JuliaLang/juliaup) and using Jupyter kernel named `Julia release channel`, we might see `isinteractive()` is `false`. The difference in the result of `isinteractive()` can affect the output of a data visualization program after execution, leading to confusion for Tensors4Fields developers.
#

# %%
fig, ax = plt.subplots()
ax.set_title("isinteractive()=$(isinteractive())")
x = [1, 2, 3]
y = [3, 1, 2]
ax.plot(x, y, marker="+")
display(fig)

# %%
fig, ax = plt.subplots()
x = [1, 2, 3]
y = [3, 1, 2]
ax.plot(x, y, marker="+")
if isinteractive()
    ax.set_title("isinteractive()=$(isinteractive())")
    # `display(fig)` causes duplicate plot.

    #=
    Add suppress redundant output such as "Python: Text(0.5, 1.0, 'isinteractive()=true')".
    This is an optional.
    =#
    nothing
else
    ax.set_title("isinteractive()=$(isinteractive())")
    display(fig) # This line is required to output results on non-interactive sessions
end

# %%
using PythonCall: PythonCall
using PythonPlot: pyplot as plt, Figure
fig, axis = plt.subplots()
data = zeros(513, 513)
c = axis.pcolor(data, cmap="RdBu_r", vmin=-1, vmax=1)
fig.colorbar(c, ax=axis)
display(gcf())
